### ISSUE TITLE
Docker GPU images don't use semantic versioning

### ISSUE THREAD

**Issue by ali-sx** [OpenDroneMap/ODM#1598]
### How did you install ODM? (Docker, installer, natively, ...)?

NA

### What is the problem?

ODM GPU docker images don't use semantic versioning compared to the CPU image.

From `publish-docker-and-wsl.yaml` : 
```
- name: Docker meta
  id: docker_meta
  uses: crazy-max/ghaction-docker-meta@v1
  with:
    images: opendronemap/odm
    tag-semver: |
      {{version}}
```

Compared to `publish-docker-gpu.yaml` : 
```
- name: Build and push Docker image
  id: docker_build
  uses: docker/build-push-action@v2
  with:
    file: ./gpu.Dockerfile
    platforms: linux/amd64
    push: true
    no-cache: true
    tags: opendronemap/odm:gpu
```

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The GPU image should use the same versioning as the CPU one. The GPU images are always overwritten by the latest version.

### How can we reproduce this? What steps did you do to trigger the problem? If this is an issue with processing a dataset, YOU MUST include a copy of your dataset uploaded on Google Drive or Dropbox (otherwise we cannot reproduce this).

NA
